version: "3"

services:
  pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:328.0.0
    command: >
      gcloud beta emulators pubsub start
      --project=pubsub-emulator
      --host-port=0.0.0.0:8080
    networks:
      - fizz-net

  fizzlibs:
    build: .
    ports:
      - 8085:8085
    volumes:
      - ./:/app
    environment:
      GKE_SOFTWARE_ID: 'fizzlibs-local'
      PUBSUB_EMULATOR_HOST: pubsub:8080
      QQUEUE_PROJECT_ID: pubsub-emulator
      HTTP_SCHEME: http
      HTTP_HOST: fizzlibs:8085
    networks:
      - fizz-net

networks:
  fizz-net:
    driver: bridge
